//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceManagerService.ParcelService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ParcelService.ParcelServiceSoap")]
    public interface ParcelServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmailNotifications", ReplyAction="*")]
        bool SendEmailNotifications();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RefreshTransactions", ReplyAction="*")]
        bool RefreshTransactions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProductPrice", ReplyAction="*")]
        bool UpdateProductPrice(int timeDelay);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateProductRank", ReplyAction="*")]
        bool UpdateProductRank();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ParcelServiceSoapChannel : PriceManagerService.ParcelService.ParcelServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ParcelServiceSoapClient : System.ServiceModel.ClientBase<PriceManagerService.ParcelService.ParcelServiceSoap>, PriceManagerService.ParcelService.ParcelServiceSoap {
        
        public ParcelServiceSoapClient() {
        }
        
        public ParcelServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ParcelServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParcelServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ParcelServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SendEmailNotifications() {
            return base.Channel.SendEmailNotifications();
        }
        
        public bool RefreshTransactions() {
            return base.Channel.RefreshTransactions();
        }
        
        public bool UpdateProductPrice(int timeDelay) {
            return base.Channel.UpdateProductPrice(timeDelay);
        }
        
        public bool UpdateProductRank() {
            return base.Channel.UpdateProductRank();
        }
    }
}
